package artifacts

import "errors"

var (
	ErrInvalidDataClass                              = errors.New("invalid data class")
	ErrReservedDataClassDisabled                     = errors.New("reserved data class is disabled")
	ErrInvalidDigest                                 = errors.New("invalid digest")
	ErrArtifactNotFound                              = errors.New("artifact not found")
	ErrFlowDenied                                    = errors.New("artifact flow denied")
	ErrFlowProducerRoleMismatch                      = errors.New("artifact producer role does not match flow request")
	ErrUnapprovedEgressDenied                        = errors.New("unapproved excerpt egress denied")
	ErrApprovedEgressRequiresManifest                = errors.New("approved excerpt egress requires manifest opt-in")
	ErrApprovedExcerptRevoked                        = errors.New("approved excerpt is revoked")
	ErrQuotaExceeded                                 = errors.New("artifact quota exceeded")
	ErrMissingApprovalMetadata                       = errors.New("approval request missing required metadata")
	ErrApprovalContentNotVisible                     = errors.New("approval requires full content visibility")
	ErrApprovalBulkConfirmationNeeded                = errors.New("bulk promotion requires separate approval")
	ErrPromotionRateLimited                          = errors.New("promotion requests rate limited")
	ErrPromotionTooLarge                             = errors.New("promotion request too large")
	ErrPromotionRequiresApproval                     = errors.New("promotion requires explicit human approval")
	ErrApprovalRequestArtifactRequired               = errors.New("promotion requires signed approval request artifact")
	ErrApprovalArtifactRequired                      = errors.New("promotion requires signed approval decision artifact")
	ErrVerifierNotFound                              = errors.New("promotion verifier record not found in trusted store")
	ErrApprovalVerificationFailed                    = errors.New("approval verification failed")
	ErrPromotionSourceNotUnapproved                  = errors.New("promotion source artifact must be unapproved_file_excerpts")
	ErrDataClassMutationDenied                       = errors.New("data class mutation denied")
	ErrHashOnlyHandoffRequired                       = errors.New("hash-only handoff is required")
	ErrTrustedCreatedByRoleRequired                  = errors.New("trusted source requires non-empty created_by_role")
	errUnsupportedRevocationTarget                   = errors.New("only approved_file_excerpts can be revoked")
	ErrApprovedClassRequiresPromotion                = errors.New("approved_file_excerpts must be produced via promotion")
	ErrBackupSignatureMissing                        = errors.New("backup signature file is missing")
	ErrBackupSignatureInvalid                        = errors.New("backup signature verification failed")
	ErrTrustedVerifierStateUnavailable               = errors.New("trusted verifier state unavailable")
	ErrApprovalPolicyDecisionRequired                = errors.New("approval requires policy decision hash")
	ErrDependencyCacheAmbiguousReuse                 = errors.New("dependency cache ambiguous partial reuse")
	ErrDependencyCacheUnverifiableIdentity           = errors.New("dependency cache identity is unverifiable")
	ErrDependencyCacheIncompleteState                = errors.New("dependency cache state is incomplete")
	ErrDependencyCacheTrustedSourceRequired          = errors.New("dependency cache artifacts require trusted source")
	ErrDependencyArtifactEgressDenied                = errors.New("dependency cache artifacts are internal handoff only")
	ErrSessionIdempotencyKeyConflict                 = errors.New("session idempotency key payload mismatch")
	ErrSessionExecutionTriggerIdempotencyKeyConflict = errors.New("session execution trigger idempotency key payload mismatch")
	ErrSessionActiveTurnExecutionExists              = errors.New("session already has an active turn execution")
	ErrSessionTurnExecutionNotFound                  = errors.New("session turn execution not found")
	ErrSessionTurnExecutionNotResumable              = errors.New("session has no current or resumable turn execution")
)
