//go:build runecode_tui_snapshot

package main

func snapshotBundleSpecs() map[snapshotAuditBundle]snapshotBundleSpec {
	return map[snapshotAuditBundle]snapshotBundleSpec{
		snapshotBundleFullAudit: {
			Name: snapshotBundleFullAudit,
			Scenarios: []string{
				"dashboard-healthy-empty",
				"dashboard-approval-waiting",
				"dashboard-blocked",
				"dashboard-degraded",
				"dashboard-toast-info",
				"command-mode-draft",
				"command-mode-error",
				"overlay-command-palette",
				"overlay-session-switcher",
				"quit-confirm-chat-compose",
				"quit-confirm-command-entry",
				"quit-confirm-provider-secret",
				"dashboard-focus-nav",
				"leader-help-root",
				"chat-active-session",
				"chat-compose-open",
				"runs-active-detail",
				"runs-focus-inspector",
				"runs-raw-detail",
				"approvals-pending-detail",
				"approvals-structured-detail",
				"action-center-triage",
				"artifacts-evidence-detail",
				"artifacts-structured-detail",
				"audit-degraded-detail",
				"audit-raw-detail",
				"status-ready-overview",
				"status-degraded-overview",
				"model-providers-credential-needed",
				"model-providers-secret-entry",
				"git-setup-identity-needed",
				"git-setup-provider-linked",
				"git-remote-approval-ready",
				"git-remote-executed",
				"git-remote-fail-closed",
			},
			Routes: []routeID{routeDashboard, routeChat, routeRuns, routeApprovals, routeAction, routeArtifacts, routeAudit, routeStatus, routeProviders, routeGitSetup, routeGitRemote},
		},
		snapshotBundleDashboard:     {Name: snapshotBundleDashboard, Scenarios: []string{"dashboard-healthy-empty", "dashboard-approval-waiting", "dashboard-blocked", "dashboard-degraded", "dashboard-toast-info", "dashboard-focus-nav"}, Routes: []routeID{routeDashboard}},
		snapshotBundleActionCenter:  {Name: snapshotBundleActionCenter, Scenarios: []string{"action-center-triage"}, Routes: []routeID{routeAction}},
		snapshotBundleRuns:          {Name: snapshotBundleRuns, Scenarios: []string{"runs-active-detail", "runs-focus-inspector", "runs-raw-detail", "artifacts-evidence-detail", "artifacts-structured-detail"}, Routes: []routeID{routeRuns, routeArtifacts}},
		snapshotBundleApprovals:     {Name: snapshotBundleApprovals, Scenarios: []string{"approvals-pending-detail", "approvals-structured-detail"}, Routes: []routeID{routeApprovals}},
		snapshotBundleAudit:         {Name: snapshotBundleAudit, Scenarios: []string{"audit-degraded-detail", "audit-raw-detail"}, Routes: []routeID{routeAudit}},
		snapshotBundleStatus:        {Name: snapshotBundleStatus, Scenarios: []string{"status-ready-overview", "status-degraded-overview"}, Routes: []routeID{routeStatus}},
		snapshotBundleSetup:         {Name: snapshotBundleSetup, Scenarios: []string{"model-providers-credential-needed", "model-providers-secret-entry", "git-setup-identity-needed", "git-setup-provider-linked", "git-remote-approval-ready", "git-remote-executed", "git-remote-fail-closed"}, Routes: []routeID{routeProviders, routeGitSetup, routeGitRemote}},
		snapshotBundleChat:          {Name: snapshotBundleChat, Scenarios: []string{"chat-active-session", "chat-compose-open"}, Routes: []routeID{routeChat}},
		snapshotBundleShell:         {Name: snapshotBundleShell, Scenarios: []string{"command-mode-draft", "command-mode-error", "overlay-command-palette", "overlay-session-switcher", "quit-confirm-chat-compose", "quit-confirm-command-entry", "quit-confirm-provider-secret", "leader-help-root"}, Routes: []routeID{routeDashboard, routeChat, routeProviders}},
		snapshotBundleNarrowMobile:  {Name: snapshotBundleNarrowMobile, Scenarios: []string{"narrow-sidebar-overlay", "narrow-inspector-overlay"}, Routes: []routeID{routeDashboard, routeRuns}},
		snapshotBundleNarrowCompact: {Name: snapshotBundleNarrowCompact, Scenarios: []string{"narrow-sidebar-overlay-compact", "narrow-inspector-overlay-compact"}, Routes: []routeID{routeDashboard, routeRuns}},
	}
}
